// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: buffers.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// BufInfo is an informational structure describing a buffer
// open in the current Vim session.
type BufInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// buffer number
	Bufnr int64 `protobuf:"varint,1,opt,name=bufnr,proto3" json:"bufnr,omitempty"`
	// TRUE if the buffer is modified
	Changed bool `protobuf:"varint,2,opt,name=changed,proto3" json:"changed,omitempty"`
	// Number of changes made to the buffer
	ChangedTick int64 `protobuf:"varint,3,opt,name=changed_tick,json=changedTick,proto3" json:"changed_tick,omitempty"`
	// TRUE if the buffer is hidden
	Hidden bool `protobuf:"varint,4,opt,name=hidden,proto3" json:"hidden,omitempty"`
	// Timestamp in seconds
	LastUsed int64 `protobuf:"varint,5,opt,name=last_used,json=lastUsed,proto3" json:"last_used,omitempty"`
	// TRUE if the buffer is listed
	Listed bool `protobuf:"varint,6,opt,name=listed,proto3" json:"listed,omitempty"`
	// Line number used for the buffer when opened in the current window.
	Lnum int64 `protobuf:"varint,7,opt,name=lnum,proto3" json:"lnum,omitempty"`
	//  Number of lines in the buffer (only valid when loaded)
	LineCount int64 `protobuf:"varint,8,opt,name=line_count,json=lineCount,proto3" json:"line_count,omitempty"`
	// TRUE if the buffer is loaded
	Loaded bool `protobuf:"varint,9,opt,name=loaded,proto3" json:"loaded,omitempty"`
	// Full path to the file in the buffer
	Name string `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	// List of signs placed in the buffer
	Signs []*BufInfo_Sign `protobuf:"bytes,11,rep,name=signs,proto3" json:"signs,omitempty"`
	// List of window-IDs that display this buffer
	Windows []int64 `protobuf:"varint,12,rep,packed,name=windows,proto3" json:"windows,omitempty"`
	// List of popup window-IDs that display this buffer
	Popups []int64 `protobuf:"varint,13,rep,packed,name=popups,proto3" json:"popups,omitempty"`
}

func (x *BufInfo) Reset() {
	*x = BufInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buffers_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BufInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BufInfo) ProtoMessage() {}

func (x *BufInfo) ProtoReflect() protoreflect.Message {
	mi := &file_buffers_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BufInfo.ProtoReflect.Descriptor instead.
func (*BufInfo) Descriptor() ([]byte, []int) {
	return file_buffers_proto_rawDescGZIP(), []int{0}
}

func (x *BufInfo) GetBufnr() int64 {
	if x != nil {
		return x.Bufnr
	}
	return 0
}

func (x *BufInfo) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

func (x *BufInfo) GetChangedTick() int64 {
	if x != nil {
		return x.ChangedTick
	}
	return 0
}

func (x *BufInfo) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

func (x *BufInfo) GetLastUsed() int64 {
	if x != nil {
		return x.LastUsed
	}
	return 0
}

func (x *BufInfo) GetListed() bool {
	if x != nil {
		return x.Listed
	}
	return false
}

func (x *BufInfo) GetLnum() int64 {
	if x != nil {
		return x.Lnum
	}
	return 0
}

func (x *BufInfo) GetLineCount() int64 {
	if x != nil {
		return x.LineCount
	}
	return 0
}

func (x *BufInfo) GetLoaded() bool {
	if x != nil {
		return x.Loaded
	}
	return false
}

func (x *BufInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BufInfo) GetSigns() []*BufInfo_Sign {
	if x != nil {
		return x.Signs
	}
	return nil
}

func (x *BufInfo) GetWindows() []int64 {
	if x != nil {
		return x.Windows
	}
	return nil
}

func (x *BufInfo) GetPopups() []int64 {
	if x != nil {
		return x.Popups
	}
	return nil
}

// GetBufInfoRequest defines the GetBufInfo rpc arguments.
type GetBufInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to BufferId:
	//	*GetBufInfoRequest_Bufn
	//	*GetBufInfoRequest_BufName
	BufferId isGetBufInfoRequest_BufferId `protobuf_oneof:"buffer_id"`
}

func (x *GetBufInfoRequest) Reset() {
	*x = GetBufInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buffers_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBufInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBufInfoRequest) ProtoMessage() {}

func (x *GetBufInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_buffers_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBufInfoRequest.ProtoReflect.Descriptor instead.
func (*GetBufInfoRequest) Descriptor() ([]byte, []int) {
	return file_buffers_proto_rawDescGZIP(), []int{1}
}

func (m *GetBufInfoRequest) GetBufferId() isGetBufInfoRequest_BufferId {
	if m != nil {
		return m.BufferId
	}
	return nil
}

func (x *GetBufInfoRequest) GetBufn() int64 {
	if x, ok := x.GetBufferId().(*GetBufInfoRequest_Bufn); ok {
		return x.Bufn
	}
	return 0
}

func (x *GetBufInfoRequest) GetBufName() string {
	if x, ok := x.GetBufferId().(*GetBufInfoRequest_BufName); ok {
		return x.BufName
	}
	return ""
}

type isGetBufInfoRequest_BufferId interface {
	isGetBufInfoRequest_BufferId()
}

type GetBufInfoRequest_Bufn struct {
	Bufn int64 `protobuf:"varint,4,opt,name=bufn,proto3,oneof"`
}

type GetBufInfoRequest_BufName struct {
	BufName string `protobuf:"bytes,5,opt,name=buf_name,json=bufName,proto3,oneof"`
}

func (*GetBufInfoRequest_Bufn) isGetBufInfoRequest_BufferId() {}

func (*GetBufInfoRequest_BufName) isGetBufInfoRequest_BufferId() {}

// GetBufInfoResponse defines the GetBufInfo rpc response.
type GetBufInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Buffers []*BufInfo `protobuf:"bytes,1,rep,name=buffers,proto3" json:"buffers,omitempty"`
}

func (x *GetBufInfoResponse) Reset() {
	*x = GetBufInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buffers_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBufInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBufInfoResponse) ProtoMessage() {}

func (x *GetBufInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_buffers_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBufInfoResponse.ProtoReflect.Descriptor instead.
func (*GetBufInfoResponse) Descriptor() ([]byte, []int) {
	return file_buffers_proto_rawDescGZIP(), []int{2}
}

func (x *GetBufInfoResponse) GetBuffers() []*BufInfo {
	if x != nil {
		return x.Buffers
	}
	return nil
}

type BufInfo_Sign struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Lnum int64  `protobuf:"varint,2,opt,name=lnum,proto3" json:"lnum,omitempty"`
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *BufInfo_Sign) Reset() {
	*x = BufInfo_Sign{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buffers_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BufInfo_Sign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BufInfo_Sign) ProtoMessage() {}

func (x *BufInfo_Sign) ProtoReflect() protoreflect.Message {
	mi := &file_buffers_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BufInfo_Sign.ProtoReflect.Descriptor instead.
func (*BufInfo_Sign) Descriptor() ([]byte, []int) {
	return file_buffers_proto_rawDescGZIP(), []int{0, 0}
}

func (x *BufInfo_Sign) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BufInfo_Sign) GetLnum() int64 {
	if x != nil {
		return x.Lnum
	}
	return 0
}

func (x *BufInfo_Sign) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_buffers_proto protoreflect.FileDescriptor

var file_buffers_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa5, 0x03, 0x0a, 0x07, 0x42, 0x75, 0x66, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x75, 0x66, 0x6e, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x62, 0x75, 0x66, 0x6e, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x5f, 0x74, 0x69,
	0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x64, 0x54, 0x69, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x68, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x12, 0x1b, 0x0a,
	0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x73, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x69,
	0x73, 0x74, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6c, 0x69, 0x73, 0x74,
	0x65, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6e, 0x75, 0x6d, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x6c, 0x6e, 0x75, 0x6d, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6c, 0x69, 0x6e, 0x65,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x29, 0x0a, 0x05, 0x73, 0x69, 0x67, 0x6e, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x75, 0x66, 0x49, 0x6e, 0x66, 0x6f,
	0x2e, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x05, 0x73, 0x69, 0x67, 0x6e, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x73, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x03, 0x52, 0x07, 0x77,
	0x69, 0x6e, 0x64, 0x6f, 0x77, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x70, 0x75, 0x70, 0x73,
	0x18, 0x0d, 0x20, 0x03, 0x28, 0x03, 0x52, 0x06, 0x70, 0x6f, 0x70, 0x75, 0x70, 0x73, 0x1a, 0x3e,
	0x0a, 0x04, 0x53, 0x69, 0x67, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6e, 0x75, 0x6d, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x6c, 0x6e, 0x75, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x53,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x42, 0x75, 0x66, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x04, 0x62, 0x75, 0x66, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x48, 0x00, 0x52, 0x04, 0x62, 0x75, 0x66, 0x6e, 0x12, 0x1b, 0x0a, 0x08, 0x62, 0x75, 0x66,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x62,
	0x75, 0x66, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x0b, 0x0a, 0x09, 0x62, 0x75, 0x66, 0x66, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x22, 0x3e, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x42, 0x75, 0x66, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x62, 0x75, 0x66,
	0x66, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x42, 0x75, 0x66, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x62, 0x75, 0x66, 0x66,
	0x65, 0x72, 0x73, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6c, 0x64, 0x65, 0x6c, 0x6f, 0x73, 0x73, 0x61, 0x2f, 0x76, 0x69, 0x6d, 0x2d, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x76, 0x69, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_buffers_proto_rawDescOnce sync.Once
	file_buffers_proto_rawDescData = file_buffers_proto_rawDesc
)

func file_buffers_proto_rawDescGZIP() []byte {
	file_buffers_proto_rawDescOnce.Do(func() {
		file_buffers_proto_rawDescData = protoimpl.X.CompressGZIP(file_buffers_proto_rawDescData)
	})
	return file_buffers_proto_rawDescData
}

var file_buffers_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_buffers_proto_goTypes = []interface{}{
	(*BufInfo)(nil),            // 0: proto.BufInfo
	(*GetBufInfoRequest)(nil),  // 1: proto.GetBufInfoRequest
	(*GetBufInfoResponse)(nil), // 2: proto.GetBufInfoResponse
	(*BufInfo_Sign)(nil),       // 3: proto.BufInfo.Sign
}
var file_buffers_proto_depIdxs = []int32{
	3, // 0: proto.BufInfo.signs:type_name -> proto.BufInfo.Sign
	0, // 1: proto.GetBufInfoResponse.buffers:type_name -> proto.BufInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_buffers_proto_init() }
func file_buffers_proto_init() {
	if File_buffers_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_buffers_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BufInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buffers_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBufInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buffers_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBufInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buffers_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BufInfo_Sign); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_buffers_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*GetBufInfoRequest_Bufn)(nil),
		(*GetBufInfoRequest_BufName)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_buffers_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_buffers_proto_goTypes,
		DependencyIndexes: file_buffers_proto_depIdxs,
		MessageInfos:      file_buffers_proto_msgTypes,
	}.Build()
	File_buffers_proto = out.File
	file_buffers_proto_rawDesc = nil
	file_buffers_proto_goTypes = nil
	file_buffers_proto_depIdxs = nil
}
